logging:
    pattern.level : '%5p [%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]'
    level:
        org.springframework: INFO


spring:
    profiles: default
    #DB
    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password:
        driverClassName: org.h2.Driver
        poolSize: 30
    #JPA
    jpa:
        database: H2
        show-sql: true
        hibernate:
          ddl-auto: update
        database-platform: org.hibernate.dialect.H2Dialect
flyway:
  baseline-on-migrate: true
  enabled: true
  locations: classpath:/db/migration
  schemas: PUBLIC