AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    serverless-app

    SAM Template for serverless-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 20 #Zeit bis der Aufruf einer Function in ein Timeout läuft (in Sekunden).
        #Environment:
          #Variables:
            #TABLE_NAME: books


Resources:

    HelloWorldFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: target/Serverless-1.0.jar
            Handler: helloworld.App::handleRequest
            Runtime: java8
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    PARAM1: VALUE
            Events:
                HelloWorld:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /hello
                        Method: get
    GetBookFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: target/Serverless-1.0.jar
            Handler: edu.hm.ba.serverless.handler.GetBookHandler::handleRequest
            Runtime: java8
            Events:
                GetBook:
                    Type: Api
                    Properties:
                        Path: /books/{isbn}
                        Method: get
    GetBooksFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: target/Serverless-1.0.jar
            Handler: edu.hm.ba.serverless.handler.GetBooksHandler::handleRequest
            Runtime: java8
            Events:
                GetBooks:
                    Type: Api
                    Properties:
                        Path: /books
                        Method: get
    CreateBookFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: target/Serverless-1.0.jar
            Handler: edu.hm.ba.serverless.handler.CreateBookHandler::handleRequest
            Runtime: java8
            Events:
                CreateBook:
                    Type: Api
                    Properties:
                        Path: /books
                        Method: post

Outputs:

    HelloWorldApi:
      Description: "API Gateway endpoint URL for Prod stage for Hello World function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

    HelloWorldFunction:
      Description: "Hello World Lambda Function ARN"
      Value: !GetAtt HelloWorldFunction.Arn

    HelloWorldFunctionIamRole:
      Description: "Implicit IAM Role created for Hello World function"
      Value: !GetAtt HelloWorldFunctionRole.Arn

    GetBookFunction:
      Description: "GetBook Lambda Function ARN"
      Value: !GetAtt GetBookFunction.Arn

    CreateBookFunction:
      Description: "CreateBook Lambda Function ARN"
      Value: !GetAtt CreateBookFunction.Arn
